### ISSUE TITLE
Node version dependency is incorrect.

### ISSUE THREAD

**Issue by duncanbeevers** [bahamas10/node-exec#8]
In the package.json, the minimum node version is [listed as 0.8.0](https://github.com/bahamas10/node-exec/blob/4edebe62641a1a38d0034521c4a8fcee6b38b353/package.json#L19). However, at [exec.js:35](https://github.com/bahamas10/node-exec/blob/4edebe62641a1a38d0034521c4a8fcee6b38b353/exec.js#L35), `Buffer.isEncoding` is used.

According to the [node.js changelogs](https://github.com/joyent/node/commit/e6ce25), `Buffer.isEncoding` was added at 0.9.1.

**Comment by bahamas10** [comment]
thanks! also as an fyi this module is deprecated as noted in the readme
